# Generated by Django 6.1.1 on 2026-09-12 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField(help_text='°C')),
                ('vibration', models.FloatField(help_text='mm/s (وحدة تمثيلية)')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_anomaly', models.BooleanField(default=False)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensor_readings', to='assets.asset')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
