# Generated by Django 5.2.17 on 2026-09-12 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulation', '0003_inventorytransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensorreading',
            name='vibration',
            field=models.FloatField(help_text='mm/s'),
        ),
    ]
