# Generated by Django 5.2.17 on 2026-09-12 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='tag_code',
            field=models.CharField(help_text='Synthetic QR / RFID tag generated automatically when registered'),
        ),
    ]
