# Generated by Django 5.2.17 on 2026-09-12 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_alter_asset_tag_code'),
        ('assets', '0003_assetevent'),
    ]

    operations = [
    ]
