from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('assets/', views.assets_page, name='assets'),
    path('assets/<int:pk>/', views.asset_detail, name='asset_detail'),
    path('assets/<int:pk>/assign/', views.asset_assign, name='asset_assign'),
    path('assets/<int:pk>/unassign/', views.asset_unassign, name='asset_unassign'),
    path('assets/<int:pk>/transfer/', views.asset_transfer, name='asset_transfer'),
    path('assets/<int:pk>/status/', views.asset_status, name='asset_status'),
    path('inventory/', views.inventory_page, name='inventory'),
    path('inventory/<int:pk>/', views.inventory_detail, name='inventory_detail'),
    path('inventory/<int:pk>/receive/', views.inventory_receive, name='inventory_receive'),
    path('inventory/<int:pk>/issue/', views.inventory_issue, name='inventory_issue'),
    path('maintenance/', views.maintenance_page, name='maintenance'),
    path('procurement/', views.procurement_page, name='procurement'),
    path('suppliers/', views.suppliers_page, name='suppliers'),
    path('suppliers/new/', views.supplier_create, name='supplier_create'),
    path('suppliers/<int:pk>/edit/', views.supplier_edit, name='supplier_edit'),
    path('users/', views.users_page, name='users'),
    path('audit-log/', views.audit_page, name='audit'),
    path('simulation/', views.simulation_page, name='simulation'),
    path('admin-console/', views.admin_console, name='admin_console'),
    path('settings/', views.settings_page, name='settings'),
    path('assets/new/', views.asset_create, name='asset_create'),
    path('assets/<int:pk>/edit/', views.asset_edit, name='asset_edit'),
    path('inventory/new/', views.inventory_create, name='inventory_create'),
    path('inventory/<int:pk>/edit/', views.inventory_edit, name='inventory_edit'),
    path('maintenance/new/', views.maintenance_create, name='maintenance_create'),
    path('maintenance/<int:pk>/edit/', views.maintenance_edit, name='maintenance_edit'),
    path('procurement/new/', views.po_create, name='po_create'),
    path('procurement/<int:pk>/edit/', views.po_edit, name='po_edit'),
    path('simulation/run/', views.run_simulation, name='run_simulation'),
    path('simulation/feed/', views.simulation_feed, name='simulation_feed'),
    path('simulation/tick/', views.simulation_tick, name='simulation_tick'),
]
