# Generated by Django 6.1.1 on 2026-09-12 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=150)),
                ('sku', models.CharField(max_length=50, unique=True)),
                ('quantity_on_hand', models.PositiveIntegerField(default=0)),
                ('reorder_level', models.PositiveIntegerField(default=10)),
                ('reorder_qty', models.PositiveIntegerField(default=50)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_items', to='assets.category')),
            ],
            options={
                'verbose_name_plural': 'inventory items',
            },
        ),
    ]
