from django.db import models
from assets.models import Asset


class SensorReading(models.Model):
    """Synthetic IoT sensor reading used by the live digital-twin engine."""

    asset = models.ForeignKey(Asset, on_delete=models.CASCADE, related_name='sensor_readings')
    temperature = models.FloatField(help_text='°C')
    vibration = models.FloatField(help_text='mm/s')
    timestamp = models.DateTimeField(auto_now_add=True)
    is_anomaly = models.BooleanField(default=False)

    class Meta:
        ordering = ['-timestamp']

    def __str__(self):
        flag = ' [ANOMALY]' if self.is_anomaly else ''
        return f"{self.asset.name} @ {self.timestamp:%Y-%m-%d %H:%M:%S}{flag}"


class SimulationEvent(models.Model):
    """Human-readable event stream generated by the continuous simulator."""

    class Severity(models.TextChoices):
        INFO = 'INFO', 'Info'
        WARNING = 'WARNING', 'Warning'
        CRITICAL = 'CRITICAL', 'Critical'

    created_at = models.DateTimeField(auto_now_add=True)
    event_type = models.CharField(max_length=40)
    message = models.CharField(max_length=300)
    severity = models.CharField(max_length=12, choices=Severity.choices, default=Severity.INFO)
    asset = models.ForeignKey(Asset, null=True, blank=True, on_delete=models.SET_NULL, related_name='simulation_events')
    actor_name = models.CharField(max_length=120, default='Simulation Engine')

    class Meta:
        ordering = ['-created_at']

    def __str__(self):
        return f"{self.created_at:%H:%M:%S} {self.event_type}: {self.message}"


class InventoryTransaction(models.Model):
    """Immutable warehouse movement generated by the live operations simulator."""

    class Movement(models.TextChoices):
        INBOUND = 'INBOUND', 'Inbound'
        OUTBOUND = 'OUTBOUND', 'Outbound'

    created_at = models.DateTimeField(auto_now_add=True)
    item = models.ForeignKey('inventory.Inventory', on_delete=models.CASCADE, related_name='simulation_transactions')
    movement = models.CharField(max_length=10, choices=Movement.choices)
    quantity = models.PositiveIntegerField()
    reference = models.CharField(max_length=80, blank=True)
    actor_name = models.CharField(max_length=120, default='Warehouse Staff')

    class Meta:
        ordering = ['-created_at']

    def __str__(self):
        return f"{self.movement} {self.quantity} x {self.item.sku}"
